package com.dni;

public enum ErrorEnDNI {
    LETRA_INCORRECTA,
    NUMERO_INCORRECTO,
    SEPARADOR_INCORRECTO,
    SIGNOS_DE_PUNTOS_INCORRECTOS,
    DNI_NULO,
    DNI_VACIO,
    FORMATO_INCORRECTO
}
